# fly.toml app configuration file generated for datingapp-7 on 2024-01-03T14:19:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp-7"
primary_region = "sin"

[build]
  image = "kyawhtay/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="duaeckjnk"
  CloudinarySettings__ApiKey="283294272627228"

[experimental]
  allowed_public_ports =[]
  auto_rollback = true

[http_service]
  http_checks=[]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
